# filename: app.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import hashlib
import hmac
import io
import re

import pandas as pd
import streamlit as st

try:
    from pypdf import PdfReader
except ImportError:
    PdfReader = None

try:
    from supabase import create_client
except ImportError:
    create_client = None


st.set_page_config(
    page_title="Bank Spend Analyzer",
    page_icon="💰",
    layout="wide",
)

CATEGORIES = [
    "Income",
    "Housing",
    "Utilities",
    "Groceries",
    "Food & Dining",
    "Transportation",
    "Fuel",
    "Shopping",
    "Entertainment",
    "Healthcare",
    "Debt Payments",
    "Investments",
    "Transfers",
    "Bank Fees",
    "Taxes",
    "Other",
]


def secrets_section(name):
    try:
        return st.secrets.get(name, {})
    except Exception:
        return {}


def clean(value):
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).strip().lower())


def require_password():
    expected = secrets_section("app").get("access_password")

    if not expected or st.session_state.get("authenticated"):
        return

    st.title("Bank Spend Analyzer")
    entered = st.text_input("App password", type="password")

    if st.button("Unlock", type="primary"):
        if hmac.compare_digest(str(entered), str(expected)):
            st.session_state.authenticated = True
            st.rerun()
        else:
            st.error("Incorrect password.")

    st.stop()


def get_database():
    if create_client is None:
        return None, "Add supabase to requirements.txt."

    settings = secrets_section("supabase")
    url = settings.get("url")
    key = settings.get("key")

    if not url or not key:
        return None, "Supabase URL or key is missing from Secrets."

    try:
        return create_client(url, key), None
    except Exception as error:
        return None, str(error)


def parse_amount(value):
    if pd.isna(value):
        return None

    text = str(value).strip()
    if not text:
        return None

    negative = text.startswith("(") and text.endswith(")")
    text = text.replace("$", "").replace(",", "")
    text = text.replace("(", "").replace(")", "")
    text = re.sub(r"[^0-9.\-]", "", text)

    number = pd.to_numeric(text, errors="coerce")
    if pd.isna(number):
        return None

    number = float(number)
    return -abs(number) if negative else number


def find_column(dataframe, keywords):
    for column in dataframe.columns:
        name = clean(column).replace("_", " ")
        if any(keyword in name for keyword in keywords):
            return column
    return None


def merchant_name(description):
    words = re.findall(r"[a-z0-9]+", clean(description))
    words = [word for word in words if len(word) > 2]
    return " ".join(words[:5]) or "Unknown merchant"


def classify(description, transaction_type):
    text = clean(description)
    transaction_type = clean(transaction_type)

    if any(
        word in text
        for word in [
            "fidelity",
            "vanguard",
            "schwab",
            "robinhood",
            "etrade",
            "wealthfront",
            "betterment",
            "brokerage",
            "stock",
            "invest",
            "crypto",
            "coinbase",
        ]
    ):
        return "Investments"

    if any(word in text for word in ["payroll", "salary", "direct deposit"]):
        return "Income"

    if transaction_type == "credit" and any(
        word in text for word in ["deposit", "refund", "interest", "dividend"]
    ):
        return "Income"

    category_words = {
        "Housing": ["rent", "mortgage", "hoa"],
        "Utilities": ["electric", "water", "internet", "verizon", "t-mobile"],
        "Groceries": ["grocery", "aldi", "kroger", "whole foods", "market"],
        "Food & Dining": ["restaurant", "cafe", "coffee", "doordash", "ubereats"],
        "Transportation": ["uber", "lyft", "transit", "parking", "toll"],
        "Fuel": ["shell", "chevron", "exxon", "bp", "fuel", "gas station"],
        "Shopping": ["amazon", "target", "costco", "walmart", "store"],
        "Entertainment": ["netflix", "spotify", "movie", "theater", "hulu"],
        "Healthcare": ["medical", "pharmacy", "doctor", "dental", "health"],
        "Debt Payments": ["loan", "credit card payment"],
        "Transfers": ["transfer", "zelle", "venmo", "cash app"],
        "Bank Fees": ["fee", "service charge", "overdraft"],
        "Taxes": ["irs", "tax", "state tax"],
    }

    for category, words in category_words.items():
        if any(word in text for word in words):
            return category

    return "Other"


def parse_fixed_width_txt(uploaded_file):
    raw_bytes = uploaded_file.getvalue()
    text = None

    for encoding in ["utf-8-sig", "utf-8", "utf-16", "cp1252", "latin-1"]:
        try:
            text = raw_bytes.decode(encoding)
            break
        except UnicodeDecodeError:
            continue

    if not text:
        raise ValueError("The TXT file could not be decoded.")

    lines = text.splitlines()
    header = next(
        (
            line
            for line in lines
            if "withdrawal amt" in line.lower()
            and "deposit amt" in line.lower()
        ),
        "",
    )

    deposit_position = header.lower().find("deposit amt")
    date_pattern = re.compile(r"^\s*(\d{2}/\d{2}/\d{2,4})\b")
    amount_pattern = re.compile(
        r"(?<![\w])(?:{{{{\(?-?\$?\d[\d,]*\.\d{2}\)}}}}?)"
    )

    rows = []
    current = None

    def finish():
        if current is None:
            return

        withdrawal = current["withdrawal"]
        deposit = current["deposit"]

        if withdrawal is None and deposit is None:
            return

        description = re.sub(
            r"\s+",
            " ",
            " ".join(current["narration"]),
        ).strip()

        rows.append(
            {
                "Date": current["date"],
                "Description": description or "Unknown transaction",
                "Debit": withdrawal,
                "Credit": deposit,
            }
        )

    for line in lines:
        if not line.strip():
            continue

        if re.fullmatch(r"[-= ]+", line.strip()):
            continue

        match = date_pattern.match(line)

        if match:
            finish()

            try:
                transaction_date = pd.to_datetime(
                    match.group(1),
                    dayfirst=True,
                    format="mixed",
                ).date()
            except Exception:
                continue

            rest = line[match.end():]
            matches = list(amount_pattern.finditer(rest))
            withdrawal = None
            deposit = None

            if len(matches) >= 2:
                transaction_match = matches[-2]
                transaction_value = parse_amount(
                    transaction_match.group(0)
                )
                absolute_position = match.end() + transaction_match.start()

                if (
                    deposit_position >= 0
                    and absolute_position >= deposit_position
                ):
                    deposit = abs(transaction_value)
                else:
                    withdrawal = abs(transaction_value)

            current = {
                "date": transaction_date,
                "narration": [
                    amount_pattern.sub(" ", rest).strip()
                ],
                "withdrawal": withdrawal,
                "deposit": deposit,
            }

        elif current is not None:
            current["narration"].append(line.strip())

    finish()

    if not rows:
        raise ValueError(
            "No transactions were found in the TXT file."
        )

    return pd.DataFrame(rows)


def read_csv_file(uploaded_file):
    raw = uploaded_file.getvalue()

    for encoding in ["utf-8-sig", "utf-8", "utf-16", "cp1252", "latin-1"]:
        try:
            text = raw.decode(encoding)
        except UnicodeDecodeError:
            continue

        for delimiter in [",", "\t", ";", "|"]:
            try:
                data = pd.read_csv(
                    io.StringIO(text),
                    sep=delimiter,
                    dtype=str,
                    engine="python",
                ).dropna(how="all")

                if len(data.columns) > 1 and not data.empty:
                    return data
            except Exception:
                continue

    raise ValueError(
        "The CSV file could not be read. Export it again as CSV."
    )


def standardize(data, source_file):
    data = data.dropna(how="all").copy()
    data.columns = [str(column).strip() for column in data.columns]

    date_column = find_column(
        data,
        ["date", "posted", "transaction date", "trans date"],
    )
    description_column = find_column(
        data,
        ["description", "memo", "details", "merchant", "payee", "name"],
    )
    amount_column = find_column(data, ["amount", "transaction amount"])
    debit_column = find_column(
        data,
        ["debit", "withdrawal", "withdrawal amt", "charge"],
    )
    credit_column = find_column(
        data,
        ["credit", "deposit", "deposit amt"],
    )

    if date_column is None:
        raise ValueError("Could not find a date column.")

    result = pd.DataFrame()

    result["transaction_date"] = pd.to_datetime(
        data[date_column],
        errors="coerce",
        dayfirst=True,
    ).dt.date

    if description_column:
        result["description"] = data[description_column].fillna("").astype(str)
    else:
        result["description"] = ""

    if debit_column or credit_column:
        debit = (
            data[debit_column].apply(parse_amount).fillna(0)
            if debit_column
            else pd.Series(0.0, index=data.index)
        )
        credit = (
            data[credit_column].apply(parse_amount).fillna(0)
            if credit_column
            else pd.Series(0.0, index=data.index)
        )

        result["amount"] = debit.abs().where(
            debit.abs() > 0,
            credit.abs(),
        )
        result["transaction_type"] = debit.abs().where(
            debit.abs() > 0,
            credit.abs(),
        ).apply(lambda value: "Debit" if value > 0 else "Credit")

    elif amount_column:
        amounts = data[amount_column].apply(parse_amount)
        result["amount"] = amounts.abs()
        result["transaction_type"] = amounts.apply(
            lambda value: "Debit"
            if pd.notna(value) and value < 0
            else "Credit"
        )
    else:
        raise ValueError("Could not find an amount column.")

    result["merchant"] = result["description"].apply(merchant_name)
    result["category"] = result.apply(
        lambda row: classify(
            row["description"],
            row["transaction_type"],
        ),
        axis=1,
    )
    result["source_file"] = source_file
    result["user_id"] = "personal"

    result = result.dropna(subset=["transaction_date", "amount"])
    result = result[result["amount"] > 0]

    if result.empty:
        raise ValueError(
            "No valid transactions were found."
        )

    base_keys = result.apply(
        lambda row: "|".join(
            [
                str(row["transaction_date"]),
                clean(row["description"]),
                f"{float(row['amount']):.2f}",
                clean(row["transaction_type"]),
            ]
        ),
        axis=1,
    )

    occurrence = base_keys.groupby(base_keys).cumcount()

    result["transaction_key"] = [
        hashlib.sha256(
            f"{base}|{number}".encode("utf-8")
        ).hexdigest()
        for base, number in zip(base_keys, occurrence)
    ]

    return result[
        [
            "transaction_key",
            "user_id",
            "transaction_date",
            "description",
            "merchant",
            "amount",
            "transaction_type",
            "category",
            "source_file",
        ]
    ]


def parse_file(uploaded_file):
    filename = uploaded_file.name.lower()

    if filename.endswith(".txt"):
        return standardize(
            parse_fixed_width_txt(uploaded_file),
            uploaded_file.name,
        )

    if filename.endswith(".csv"):
        return standardize(
            read_csv_file(uploaded_file),
            uploaded_file.name,
        )

    if filename.endswith((".xlsx", ".xls")):
        return standardize(
            pd.read_excel(uploaded_file),
            uploaded_file.name,
        )

    if filename.endswith(".pdf"):
        if PdfReader is None:
            raise ValueError("Add pypdf to requirements.txt.")

        reader = PdfReader(uploaded_file)
        rows = []

        for page in reader.pages:
            text = page.extract_text() or ""

            for line in text.splitlines():
                date_match = re.search(
                    r"\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b",
                    line,
                )
                amounts = re.findall(
                    r"-?{{{{\(?\$?\d[\d,]*\.\d{2}\)}}}}?",
                    line,
                )

                if date_match and amounts:
                    rows.append(
                        {
                            "Date": date_match.group(0),
                            "Description": line,
                            "Amount": parse_amount(amounts[-1]),
                        }
                    )

        if not rows:
            raise ValueError("No transactions found in the PDF.")

        return standardize(
            pd.DataFrame(rows),
            uploaded_file.name,
        )

    raise ValueError("Use TXT, CSV, XLSX, XLS, or PDF.")


def load_transactions(database):
    response = (
        database.table("transactions")
        .select("*")
        .eq("user_id", "personal")
        .order("transaction_date", desc=True)
        .execute()
    )

    data = pd.DataFrame(response.data or [])

    if data.empty:
        return data

    data["transaction_date"] = pd.to_datetime(
        data["transaction_date"],
        errors="coerce",
    ).dt.date
    data["amount"] = pd.to_numeric(data["amount"], errors="coerce")
    data["category"] = data["category"].fillna("Other")
    data["merchant"] = data["merchant"].fillna("")
    data["transaction_type"] = data["transaction_type"].fillna("Debit")

    return data


def load_rules(database):
    response = (
        database.table("category_rules")
        .select("*")
        .eq("user_id", "personal")
        .execute()
    )

    rules = {}

    for row in response.data or []:
        merchant = row.get("merchant") or row.get("pattern")
        category = row.get("final_category") or row.get("category")

        if merchant and category:
            rules[clean(merchant)] = category

    return rules


def save_transactions(database, data):
    if data.empty:
        raise ValueError("No usable transaction records were found.")

    records = data.to_dict("records")

    for start in range(0, len(records), 500):
        batch = [
            {
                "transaction_key": str(row["transaction_key"]),
                "user_id": "personal",
                "transaction_date": str(row["transaction_date"]),
                "description": str(row["description"]),
                "merchant": str(row["merchant"]),
                "amount": float(row["amount"]),
                "transaction_type": str(row["transaction_type"]),
                "category": str(row["category"]),
                "source_file": str(row["source_file"]),
            }
            for row in records[start:start + 500]
        ]

        database.table("transactions").upsert(
            batch,
            on_conflict="transaction_key",
        ).execute()


def save_category_changes(database, original, edited):
    old_categories = original.set_index(
        "transaction_key"
    )["category"].to_dict()

    changed = 0

    for _, row in edited.iterrows():
        key = str(row["transaction_key"])
        category = str(row["category"]).strip() or "Other"

        if category == str(old_categories.get(key)):
            continue

        database.table("transactions").update(
            {"category": category}
        ).eq(
            "transaction_key",
            key,
        ).execute()

        merchant = str(row["merchant"]).strip()

        if merchant:
            database.table("category_rules").upsert(
                {
                    "user_id": "personal",
                    "merchant": merchant,
                    "final_category": category,
                    "pattern": merchant,
                    "category": category,
                },
                on_conflict="user_id,merchant",
            ).execute()

        changed += 1

    return changed


require_password()

st.title("Bank Spend Analyzer")
st.caption("Upload, review, and categorize every transaction.")

database, database_error = get_database()

if database_error:
    st.sidebar.warning(database_error)

if "data" not in st.session_state:
    st.session_state.data = (
        load_transactions(database)
        if database is not None
        else pd.DataFrame()
    )

with st.sidebar:
    st.header("Import statement")

    uploaded_file = st.file_uploader(
        "Upload TXT, CSV, Excel, or PDF",
        type=["txt", "csv", "xlsx", "xls", "pdf"],
    )

    if st.button("Import statement", type="primary"):
        if uploaded_file is None:
            st.warning("Choose a file first.")
        elif database is None:
            st.error("Supabase is not connected.")
        else:
            try:
                imported = parse_file(uploaded_file)
                rules = load_rules(database)

                for index, row in imported.iterrows():
                    saved_category = rules.get(
                        clean(row["merchant"])
                    )
                    if saved_category:
                        imported.at[index, "category"] = saved_category

                save_transactions(database, imported)
                st.session_state.data = load_transactions(database)
                st.success(
                    f"Imported {len(imported)} transaction(s)."
                )
                st.rerun()
            except Exception as error:
                st.exception(error)

data = st.session_state.data

if data.empty:
    st.info("Upload a statement to begin.")
    st.stop()

data["transaction_date"] = pd.to_datetime(
    data["transaction_date"],
    errors="coerce",
).dt.date

data["category"] = data["category"].fillna("Other")
data["merchant"] = data["merchant"].fillna("")

min_date = min(data["transaction_date"])
max_date = max(data["transaction_date"])

with st.sidebar:
    selected_dates = st.date_input(
        "Date range",
        value=(min_date, max_date),
        min_value=min_date,
        max_value=max_date,
    )

if isinstance(selected_dates, (tuple, list)):
    start_date, end_date = selected_dates
else:
    start_date = end_date = selected_dates

filtered = data[
    data["transaction_date"].between(start_date, end_date)
].copy()

if filtered.empty:
    st.warning("No transactions match the selected dates.")
    st.stop()

debits = filtered[
    filtered["transaction_type"].str.lower() == "debit"
]["amount"].sum()

credits = filtered[
    filtered["transaction_type"].str.lower() == "credit"
]["amount"].sum()

first, second, third, fourth = st.columns(4)
first.metric("Transactions", f"{len(filtered):,}")
second.metric("Spending", f"${debits:,.2f}")
third.metric("Income", f"${credits:,.2f}")
fourth.metric("Net", f"${credits - debits:,.2f}")

st.subheader("Review and categorize all transactions")
st.caption("Edit any category, then save your changes.")

review_columns = [
    "transaction_key",
    "transaction_date",
    "description",
    "merchant",
    "amount",
    "transaction_type",
    "category",
]

review_data = filtered[review_columns].copy()

edited_data = st.data_editor(
    review_data,
    hide_index=True,
    use_container_width=True,
    num_rows="fixed",
    key="transaction_editor",
    column_config={
        "transaction_key": None,
        "transaction_date": st.column_config.DateColumn("Date"),
        "description": st.column_config.TextColumn("Description"),
        "merchant": st.column_config.TextColumn("Merchant"),
        "amount": st.column_config.NumberColumn(
            "Amount",
            format="$%.2f",
        ),
        "transaction_type": st.column_config.TextColumn("Type"),
        "category": st.column_config.SelectboxColumn(
            "Category",
            options=CATEGORIES,
            required=True,
        ),
    },
    disabled=[
        "transaction_date",
        "description",
        "merchant",
        "amount",
        "transaction_type",
    ],
)

if st.button("Save category changes", type="primary"):
    try:
        changed = save_category_changes(
            database,
            review_data,
            edited_data,
        )
        st.session_state.data = load_transactions(database)
        st.success(f"Saved {changed} category change(s).")
        st.rerun()
    except Exception as error:
        st.exception(error)

st.subheader("Monthly spending")

expenses = filtered[
    filtered["transaction_type"].str.lower() == "debit"
].copy()

if expenses.empty:
    st.info("No debit transactions available.")
else:
    expenses["month"] = pd.to_datetime(
        expenses["transaction_date"]
    ).dt.to_period("M").astype(str)

    monthly = expenses.groupby("month")["amount"].sum()
    st.line_chart(monthly)
